if {

} elif {

} else {

}

a := if a>1 {
 return a
 } else {
 return 1
 }

var if f{
   111111  
|| 22222    
|| 33333   
&& -- 444444 
   -- || pppp
   -- && -- vvvv
         -- || lll
         -- && -- ooo
               -- && aaa
&& 5555555  
&& 666666  
|| 7777777
}

if @f {

}

if true {} <=> if !false {}

 if a == false {} 
 where  a==1 or a == 2 and b == 2 {}
 where  a in 1...2 {}
 where  a in 1...10 {}


